# Generated by Django 2.0.2 on 2018-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('password', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('confirm_password', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
