# Generated by Django 2.0.2 on 2018-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='activation_key',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
