# Generated by Django 2.0.2 on 2018-10-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='confirm_password',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact_number',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.TextField(max_length=100),
        ),
    ]
