# Generated by Django 2.0.2 on 2018-10-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20181016_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='address',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='confirm_password',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact_number',
            field=models.TextField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='head_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
