# Generated by Django 2.0.2 on 2018-10-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_of_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_volunteers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers_volunteered',
            field=models.IntegerField(default=0),
        ),
    ]
