# Generated by Django 2.0.2 on 2018-10-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20181016_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
    ]
