# Generated by Django 2.0.2 on 2018-10-16 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_event_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
    ]
