# Generated by Django 2.0.2 on 2018-10-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organisation', '0009_auto_20181016_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organisation',
        ),
        migrations.AddField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
